### ISSUE TITLE
gm binaries issue

### ISSUE THREAD

**Issue by maxogden** [ngoldman/himawari-bg#1]
~/Desktop/cats 🐈  himawari-bg
Downloading satellite images [====================] 100% 0.0s
[Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "-page" "+0+0" "tmp/0_0.png" "-page" "+0+550" "tmp/0_1.png" "-page" "+0+1100" "tmp/0_2.png" "-page" "+0+1650" "tmp/0_3.png" "-page" "+550+0" "tmp/1_0.png" "-page" "+550+550" "tmp/1_1.png" "-page" "+550+1100" "tmp/1_2.png" "-page" "+550+1650" "tmp/1_3.png" "-page" "+1100+0" "tmp/2_0.png" "-page" "+1100+550" "tmp/2_1.png" "-page" "+1100+1100" "tmp/2_2.png" "-page" "+1100+1650" "tmp/2_3.png" "-page" "+1650+0" "tmp/3_0.png" "-page" "+1650+550" "tmp/3_1.png" "-page" "+1650+1100" "tmp/3_2.png" "-page" "+1650+1650" "tmp/3_3.png" "-mosaic" "/Users/max/Pictures/himawari-images/1455001394594.jpg" this most likely means the gm/convert binaries can't be found]
~/Desktop/cats 🐈  brew install imagemagick
Warning: imagemagick-6.9.2-8 already installed

`¯\_(ツ)_/¯`

**Comment by ngoldman** [comment]
oh sorry bout that :(((

Forgot graphicsmagick is required. Depends on https://github.com/jakiestfu/himawari.js.

**Comment by ngoldman** [comment]
I added a warning and instructions in the install. Ideally would like to not have dependencies that can't be npm installed, but for now `¯\_(ツ)_/¯`

https://github.com/ngoldman/himawari-bg/blob/master/README.md#install

**Comment by maxogden** [comment]
ah i didnt even realize those were separate projects, thanks
