### ISSUE TITLE
bg image wasn't wide enough

### ISSUE THREAD

**Issue by maxogden** [ngoldman/himawari-bg#4]
on a macbook 12"

<img width="1280" alt="screen shot 2016-02-09 at 10 41 04 am" src="https://cloud.githubusercontent.com/assets/39759/12926755/b8fab15c-cf19-11e5-9f7c-051c391f5a0c.png">

**Comment by ngoldman** [comment]
You gotta set the bg color yourself. I guess I could detect screen size and fill the image to size

**Comment by maxogden** [comment]
oh ok

**Comment by ngoldman** [comment]
See note at bottom of usage :point_right: https://github.com/ngoldman/himawari-bg#usage

Think it's worth doing the screen size detection and fill? For now it's just taking whatever image is handed off from `himawari.js` and passing that to `wallpaper`.

**Comment by maxogden** [comment]
Ooh turns out when I changed this before setting it then it did what I
wanted
[image: Inline image 1]
Before I had it on 'Center'

**Comment by ngoldman** [comment]
Marking this as resolved for now :sparkles:
