### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by Fuck-You-GFW** [ngoldman/himawari-bg#5]
```
$ node ngoldman-himawari-bg-example.js
Downloading satellite images [==                  ] 12% 797.2sstream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: ETIMEDOUT
    at null._onTimeout (/Users/Kiven/node_modules/himawari-bg/node_modules/himawari/node_modules/request/request.js:762:15)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by ngoldman** [comment]
This appears to be an unhandled timeout error in `himawari.js`. I'll report this issue in that repo and keep this open for reference until it's resolved.

**Comment by ngoldman** [comment]
This appears to be resolved in the latest release of `himawari.js` (see https://github.com/jakiestfu/himawari.js/issues/5). If you reinstall `himawari-bg` it should us the latest version of `himawari.js`. I'll bump the dependency to ensure this doesn't happen in future releases. Please let me know if you have any further issues.
